modLoader="javafml"
loaderVersion="[25,)"
authors="David Ma"

[[mods]]
modId="tinymobfarm"
version="1.0.5"
displayName="Tiny Mob Farm"
description='A Minecraft Mod that adds single block mob farms that generates mob drops passively.'